apiVersion: v2
name: nginx-proxy
description: NGINX reverse proxy for orchestrated-ping service
type: application
version: 1.0.0
appVersion: "1.25.3"

keywords:
  - nginx
  - proxy
  - reverse-proxy

maintainers:
  - name: arifjehoh

dependencies: []
