{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "go-ping.fullname" . }}
  labels:
    {{- include "go-ping.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "go-ping.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}